version: '3.8'

services:
  db:
    container_name: db
    image: postgres:16.2-alpine3.19
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
    restart: always
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "4200:4200"
    restart: always


volumes:
  db_data:
