version: '3.8'

services:
  db:
    container_name: db
    build: mongo
    env_file:
      - .env
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
      - db_config:/data/configdb
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
    restart: always
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always
    links:
      - db
    depends_on:
      - backend


volumes:
  db_data:
  db_config:
