server:
#  ssl:
#    key-store-type: PKCS12
#    key-store: classpath:keystore/wave.p12
#    key-store-password: test123
#    key-password: test123
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: dev
app:
  endpoints:
    post-target: /competions/{competitionId}/competitors/{competitorId}/targets
    get-competitors: /competitors
    is-alive: /is-alive
    get-name: /name
